name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - deploy-test

env:
  AZURE_WEBAPP_NAME: DBUxCheckmateMain
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DB_STRING_SECRET: ${{ secrets.DB_STRING_SECRET }}

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./Uxcheckmate/Uxcheckmate.sln

      - name: Build
        run: dotnet build ./Uxcheckmate/Uxcheckmate.sln --configuration Release --no-restore

      - name: Install missing Linux dependencies for Playwright
        run: |
          echo "🔧 Installing Playwright Linux dependencies..."
          npx playwright install-deps
        env:
          DEBUG: pw:*

      - name: Checkpoint:Linux dependencies installed
        run: echo "✅ Playwright Linux dependencies installed successfully."

      - name: Install Playwright v1.50.0
        run: |
          echo "📦 Installing Playwright v1.50.0..."
          npm install playwright@1.50.0
          npx playwright install
        env:
          DEBUG: pw:*

      - name: Checkpoint:Playwright install complete
        run: echo "✅ Playwright installed and browsers set up."

      - name: Verify Playwright Installation
        run: |
          echo "🧪 Verifying Playwright installation..."
          if ! [ -x "$(command -v npx)" ]; then
            echo '❌ Error: npx is not installed.' >&2
            exit 1
          fi
          npx playwright --version

      - name: Publish
        run: dotnet publish ./Uxcheckmate/Uxcheckmate_Main/Uxcheckmate_Main.csproj --configuration Release --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Copy Playwright Browsers to publish folder
        run: |
          echo "📁 Copying Playwright browsers to publish folder..."
          mkdir -p '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/playwright/lol/.cache'
          cp -r ~/.cache/ms-playwright '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/playwright/.cache/ms-playwright'

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
