name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  AZURE_WEBAPP_NAME: DBUxCheckmateMain
  AZURE_WEBAPP_PACKAGE_PATH: './Uxcheckmate/Uxcheckmate_Main/bin/Release/net9.0/publish'
  DB_STRING_SECRET: ${{ secrets.DB_STRING_SECRET }}

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./Uxcheckmate/Uxcheckmate_Main/Uxcheckmate_Main.sln

      - name: Build
        run: dotnet build ./Uxcheckmate/Uxcheckmate_Main/Uxcheckmate_Main.sln --configuration Release --no-restore

      - name: Install Node.js for Playwright
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install missing Linux dependencies for Playwright
        run: |
          echo "🔧 Installing Playwright Linux dependencies..."
          cd Uxcheckmate/Uxcheckmate_Main
          npm install
        env:
          DEBUG: pw:*

      - name: Install Playwright v1.50.0
        run: |
          echo "📦 Installing Playwright v1.50.0..."
          export PLAYWRIGHT_BROWSERS_PATH=${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/ms-playwright
          cd Uxcheckmate/Uxcheckmate_Main
          npm install playwright@1.50.0
          npx playwright install chromium
        env:
          PLAYWRIGHT_BROWSERS_PATH: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/ms-playwright
          DEBUG: pw:*

      - name: Verify Playwright installation
        run: |
          ls -la ./Uxcheckmate/Uxcheckmate_Main/bin/Release/net9.0/publish/ms-playwright

      - name: Show browser location in publish path
        run: |
          echo "Checking Playwright browser location: "
          find ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/ms-playwright -name "chrome*" | head -n 5

      - name: Clear previous build causing loops
        run: rm -rf ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publish
        run: dotnet publish ./Uxcheckmate/Uxcheckmate_Main/Uxcheckmate_Main.csproj -c Release -o ./Uxcheckmate/Uxcheckmate_Main/bin/Release/net9.0/publish

      - name: Create test file
        run: |
          echo "Deployment test file. Created at $(date)" > ./Uxcheckmate/Uxcheckmate_Main/bin/Release/net9.0/publish/deployment-test.txt

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
