name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - deploy-test

env:
  AZURE_WEBAPP_NAME: DBUxCheckmateMain
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DB_STRING_SECRET: ${{ secrets.DB_STRING_SECRET }}

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./Uxcheckmate/Uxcheckmate.sln

      - name: Build
        run: dotnet build ./Uxcheckmate/Uxcheckmate.sln --configuration Release --no-restore

      - name: Install missing Linux dependencies for Playwright
        run: npx playwright install-deps

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Publish
        run: dotnet publish ./Uxcheckmate/Uxcheckmate_Main/Uxcheckmate_Main.csproj --configuration Release --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Copy Playwright Browsers to publish folder
        run: |
          mkdir -p '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/playwright/.cache'
          cp -r ~/.cache/ms-playwright '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/playwright/.cache/ms-playwright'

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
