name: Publish 🚀

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: UxCheckmateMain
  AZURE_CONTAINER_REGISTRY: uxcheckmateregistry.azurecr.io
  IMAGE_NAME: uxcheckmateapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies and run Playwright tests
      run: |
        cd Uxcheckmate
        npm install
        npx playwright install --with-deps
        npx playwright test --reporter html

    - name: Build and publish the application
      run: |
        cd Uxcheckmate
        dotnet restore Uxcheckmate.csproj
        dotnet publish Uxcheckmate.csproj -c Release -o ./publish
        mkdir -p ./publish/html-report
        cp -r ./html-report/* ./publish/html-report/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Uxcheckmate  
        file: ./Dockerfile
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
